'use strict';

//given string
let str = '2696286';
console.log(str + ' is a ' + typeof str);

function strToNum(string) {
    //declare new variable as number 0 and len represent input length
    let len = string.length;
    let result = 0;
    
    function convert(bool) {
        let i, dP, dPLooped = 0;

        //init loop's starting position
        bool ? i = 1 : i = 0;

        for(i; i < string.length; i ++) {
            //convert string to integer by ascii code
            let ascii = string[i].charCodeAt(0) - 48;
            //invert i
            let num = -i + len - 1;

            dP ? dPLooped += 1 : null;
           
            //check if string includes decimal point
            if(string[i] === '.') {
                dP = true;
                //ignore returned ascii code
                ascii = 0;
                //remove uneccesary digit generated by '.'
                result /= 10;
            }
            
            if(bool) {
                result -= ascii * Math.pow(10, num);
            } else {
                result += ascii * Math.pow(10, num);
            }
        }
        //put decimal point on the right place
        result /= Math.pow(10, dPLooped);
        console.log(result + ' is now a ' + typeof result);
    }
    //check if string includes nagtive sign
    string[0] === '-' ? convert(true) : convert(false);
}
strToNum(str);